# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 3s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: 'node'
  file_sd_configs:
  - files:
    - 'targets.json'

