version: '3.8'
services:
  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    volumes:
      - "./conf/:/usr/local/kong/declarative:ro"
    env_file:
      - kong.env